### ISSUE TITLE
firebase unable to link facebook provider to email provider on master branch

### ISSUE THREAD

**Issue by j2emanue** [SUPERCILEX/FirebaseUI-Android#27]
Hi Alex, can you take a look at your build and tell me if quickly if it works for you ?  i've pulled your latest code.  im referring to issue https://github.com/firebase/FirebaseUI-Android/issues/1275 .   Could you try it. your master branch in particular is what i am using and i havent changed anything its just not working when using facebook account to link with email provider. 

here are the details:  

Regarding firebaseUI auth, i found that if an facebook account is trying to be linked with email provider there is an error of 

```
W/AccountLinker: Error linking with credential
    com.google.firebase.FirebaseException: User has already been linked to the given provider.
        at com.google.firebase.auth.api.internal.zzce.zzb(Unknown Source:221)
        at com.google.firebase.auth.api.internal.zzao.zzd(Unknown Source:35)
        at com.google.firebase.auth.FirebaseAuth.zzc(Unknown Source:15)
        at com.google.firebase.auth.FirebaseUser.linkWithCredential(Unknown Source:11)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.start(AccountLinker.java:82)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.<init>(AccountLinker.java:52)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.linkToNewUser(AccountLinker.java:65)
        at com.firebase.ui.auth.viewmodel.idp.LinkingSocialProviderResponseHandler.startSignIn(LinkingSocialProviderResponseHandler.java:43)
        at com.firebase.ui.auth.ui.idp.WelcomeBackIdpPrompt$1.onSuccess(WelcomeBackIdpPrompt.java:129)
        at com.firebase.ui.auth.ui.idp.WelcomeBackIdpPrompt$1.onSuccess(WelcomeBackIdpPrompt.java:126)
        at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:45)
        at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:14)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.firebase.ui.auth.viewmodel.OperableViewModel.setResult(OperableViewModel.java:24)
        at com.firebase.ui.auth.data.remote.FacebookSignInHandler.access$600(FacebookSignInHandler.java:39)
        at com.firebase.ui.auth.data.remote.FacebookSignInHandler$ProfileRequest.onCompleted(FacebookSignInHandler.java:172)
        at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:301)
        at com.facebook.GraphRequest$5.run(GraphRequest.java:1380)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
```

and that error is probably fine. but there  NO CALBACK to onActivityResults. instead i get a toast that an error has occured.  

Here are the steps to reproduce:

1. login with facebook

2. logout

3. signin with email provider and use the same email as the facebook account.

3b. user then get the firebaseUIAuth prompt: you've already used facebookEmail@domain.com . Sign in with facebook to continue

4. after facebook prompt appears, enter in facebook credentials (or hit continue if it does not prompt etc)

5. library gives the above error and a toast message that an error has occured. 

I also tried this with google provider instead of facebook but the same thing happens.  There is no callback in onActivityResult either. 

could you also tell me if its still a good idea to use your fork or if since now there is firebase versioning if the updates are going to come faster in the main project ?

**Comment by SUPERCILEX** [comment]
Moving to https://github.com/firebase/FirebaseUI-Android/issues/1275#issuecomment-387254366.
