### ISSUE TITLE
Updating a Phone Number: "User has already been linked to the given provider"

### ISSUE THREAD

**Issue by kiptoomm** [SUPERCILEX/FirebaseUI-Android#29]
### My environment

  * Android device: Oppo A37fw
  * Android OS version: 5.1.1
  * Google Play Services version: 15.0.0
  * Firebase/Play Services SDK version: 15.0.0
  * FirebaseUI version: `com.github.SUPERCILEX.FirebaseUI-Android:firebase-ui-auth:7382a75` (latest master)
  
### The problem:

I'm having an issue similar to a https://github.com/firebase/FirebaseUI-Android/issues/1275 but with phone numbers. I would like for my users to be able to update their auth phone numbers as they wish. 

#### Steps to reproduce:

  1. Perform the firebase-ui auth flow with the phone number option
  2. Enter user's phone number
  3. Verify phone number (confirmation code entered)
  4. Log out user
  5. Repeat step 1 to 3 
  
#### Observed Results:

  
<img width="306" alt="screen shot 2018-09-01 at 5 52 03 pm" src="https://user-images.githubusercontent.com/1447912/44947052-c81ebc00-ae0f-11e8-891f-df4d23cd2f92.png">

Stacktrace:

`09-01 17:34:20.764 21008-21008/app.example.android E/AuthUI: A sign-in error occurred.
    com.google.firebase.FirebaseException: User has already been linked to the given provider.
        at com.google.firebase.auth.api.internal.zzce.zzb(Unknown Source)
        at com.google.firebase.auth.api.internal.zzao.zzd(Unknown Source)
        at com.google.firebase.auth.FirebaseAuth.zzc(Unknown Source)
        at com.google.firebase.auth.FirebaseUser.linkWithCredential(Unknown Source)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.start(AccountLinker.java:82)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.<init>(AccountLinker.java:52)
        at com.firebase.ui.auth.util.accountlink.AccountLinker.linkWithCurrentUser(AccountLinker.java:58)
        at com.firebase.ui.auth.viewmodel.phone.PhoneProviderResponseHandler.startSignIn(PhoneProviderResponseHandler.java:37)
        at com.firebase.ui.auth.ui.phone.PhoneActivity$2.onSuccess(PhoneActivity.java:87)
        at com.firebase.ui.auth.ui.phone.PhoneActivity$2.onSuccess(PhoneActivity.java:79)
        at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:68)
        at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:18)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.firebase.ui.auth.viewmodel.OperableViewModel.setResult(OperableViewModel.java:24)
        at com.firebase.ui.auth.ui.phone.PhoneNumberVerificationHandler.submitVerificationCode(PhoneNumberVerificationHandler.java:61)
        at com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment.submitCode(SubmitConfirmationCodeFragment.java:219)
        at com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment.access$100(SubmitConfirmationCodeFragment.java:45)
        at com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment$2.onClick(SubmitConfirmationCodeFragment.java:147)
        at android.view.View.performClick(View.java:4781)
        at android.view.View$PerformClick.run(View.java:19907)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)`
  
#### Expected Results:

  * Phone number is successfully changed/updated
  
#### Relevant Code:

  ```
class ExampleMergeService: ManualMergeService() {
    override fun onLoadData(): Task<Void>? {
        //val loadTask = TaskCompletionSource<Void>()
        return null //loadTask.task
    }

    override fun onTransferData(response: IdpResponse?): Task<Void>? {
        return null
    }
}

 val providers = Arrays.asList(
                AuthUI.IdpConfig.PhoneBuilder().build())

  startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setIsSmartLockEnabled(!BuildConfig.DEBUG, true) // disable smart lock for dev/test
                        .setIsAccountLinkingEnabled(true, ExampleMergeService::class.java)
                        .build(),
                requestCode)


  ```

**Comment by SUPERCILEX** [comment]
Unfortunately, neither my fork nor the official repo supports any sort of profile updates, but it is [planned](https://github.com/firebase/FirebaseUI-Android/issues/235). To clear up any confusion, my fork is meant to link two _different_ accounts together.
